- name: openai/qwen2.5-coder
  extra_params:
    api_base: http://192.168.0.60:5000/v1
    top_p: 0.8
    top_k: 20
    temperature: 0.7
- name: openai/qwen3-coder
  extra_params:
    api_base: http://192.168.1.51:5000/v1
    top_p: 0.8
    top_k: 20
    temperature: 0.7
