#!/bin/bash

code --install-extension alefragnani.project-manager
code --install-extension asvetliakov.vscode-neovim
code --install-extension charliermarsh.ruff
code --install-extension codezombiech.gitignore
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension emeraldwalk.RunOnSave
code --install-extension esbenp.prettier-vscode
code --install-extension exiasr.hadolint
code --install-extension foxundermoon.shell-format
code --install-extension github.vscode-github-actions
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension IBM.output-colorizer
code --install-extension icrawl.discord-vscode
code --install-extension lokalise.i18n-ally
code --install-extension mechatroner.rainbow-csv
code --install-extension medo64.render-crlf
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-python.mypy-type-checker
code --install-extension ms-python.python
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension pflannery.vscode-versionlens
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension ryu1kn.partial-diff
code --install-extension shengchen.vscode-checkstyle
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension stylelint.vscode-stylelint
code --install-extension tamasfe.even-better-toml
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension usernamehw.errorlens
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vitest.explorer
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vscjava.vscode-java-pack
code --install-extension vscode-icons-team.vscode-icons
code --install-extension YoavBls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
