#!/bin/bash

extensions=(
    "alefragnani.project-manager"
    "bierner.markdown-mermaid"
    "charliermarsh.ruff"
    "continue.continue"
    "DavidAnson.vscode-markdownlint"
    "dbaeumer.vscode-eslint"
    "eamodio.gitlens"
    "esbenp.prettier-vscode"
    "expo.vscode-expo-tools"
    "foxundermoon.shell-format"
    "github.vscode-github-actions"
    "GrapeCity.gc-excelviewer"
    "Gruntfuggly.todo-tree"
    "IBM.output-colorizer"
    "james-yu.latex-workshop"
    "mechatroner.rainbow-csv"
    "medo64.render-crlf"
    "mhutchie.git-graph"
    "mikestead.dotenv"
    "msjsdiag.vscode-react-native"
    "ms-azuretools.vscode-containers"
    "ms-playwright.playwright"
    "ms-python.python"
    "ms-toolsai.jupyter"
    "ms-vscode.live-server"
    "ms-vscode-remote.remote-containers"
    "ms-vscode-remote.remote-ssh"
    "mylesmurphy.prettify-ts"
    "redhat.vscode-xml"
    "redhat.vscode-yaml"
    "ryu1kn.partial-diff"
    "streetsidesoftware.code-spell-checker"
    "tamasfe.even-better-toml"
    "tht13.rst-vscode" # Requires python3-docutils
    "timonwong.shellcheck"
    "tomoki1207.pdf"
    "usernamehw.errorlens"
    "vincaslt.highlight-matching-tag"
    "vitest.explorer"
    "vscode-icons-team.vscode-icons"
    "YoavBls.pretty-ts-errors"
    "yzhang.markdown-all-in-one"
)

for extension in "${extensions[@]}"; do
    code --install-extension "$extension"
done

